### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by duqinaerfa** [minzhou1003/API-miniproject#5]
Hi! You did quite a great job on this mini-project! You can successfully achieve all the basic required functions of the project. Besides, you wrote such a wonderful Readme file, it also help me to understand the project better. Whats more, it has no error or exception. 
You also take situations like API might fail into consideration by adding codes like "print('\nFailed to download images, please delete the /images folder and try again.')","print('Google vision API failed, please export the JSON file and try again.')","print('Failed to convert to video, please try again.')" and "print('Google video intelligence API failed, please export the JSON file and try again.')".  The code can handle exception like what if there are too many pictures as well by "if(len(alltweets) > 15): break". Although you made some spelling mistakes like"vision""again", but it's honestly not important. Generally, it's quite a good project!

**Comment by minzhou1003** [comment]
Thanks for your review. I have fixed the spelling error.
